#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  3 16:46:38 2023

@author: sofiakruse
"""

import pandas as pd
data = pd.read_csv("plants.csv")
print(data)

data1 = pd.read_csv("plantinfo.csv")
print(data1)
